module.exports = {
  collectCoverageFrom: [
    '**/*.{js,jsx,ts}',
    '!**/*.d.ts',
    '!**/.eslintrc.js',
    '!**/node_modules/**',
    '!<rootDir>/**/*types.ts',
    '!<rootDir>/packages/**/*definitions.ts',
    '!<rootDir>/packages/**/*module.ts',
    '!<rootDir>/packages/**/src/index.ts',
    '!<rootDir>/packages/**/jest.config.ts',
    '!<rootDir>/packages/**/jest.setup.ts',
    '!<rootDir>/*.config.js',
    '!<rootDir>/*.setup.js',
    '!<rootDir>/coverage/**',
    '!<rootDir>/docs/**',
    '!<rootDir>/test/**',
    '!<rootDir>/dist/**',
  ],
  coverageThreshold: {
    global: {
      lines: 70,
      branches: 70,
      functions: 70,
      statements: 70,
    },
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  moduleNameMapper: {
    '#node-web-compat': './node-web-compat-node.js',
    '^@src/(.*)$': ['<rootDir>/src/$1'],
    '^@config/(.*)$': ['<rootDir>/src/config/$1'],
    '^@database/(.*)$': ['<rootDir>/src/database/$1'],
    '^@modules/(.*)$': ['<rootDir>/src/modules/$1'],
    '^@shared/(.*)$': ['<rootDir>/src/shared/$1'],
    '^@test/(.*)$': ['<rootDir>/test/$1'],
    '^@feedma/nest-testing': ['<rootDir>/packages/testing/src/index'],
    '^@feedma/nest-testing/(.*)$': ['<rootDir>/packages/testing/src/$1'],
  },
  rootDir: '.',
  setupFiles: [],
  setupFilesAfterEnv: ['jest-extended/all', '<rootDir>/jest.setup.ts'],
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        isolatedModules: true,
      },
    ],
  },
  testEnvironment: 'node',
};
